language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - libglfw3-dev
            - cmake
            - build-essential
            - libdevil-dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_OAUTH
        file:
          - ./Engine/Engine
          - ./Generator/Generator
        on:
          repo: filipefreitas8/cg1920tp
          all_branches: true
          tags: true
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      addons:
        homebrew:
          packages:
            - glfw
            - devil
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_OAUTH
        file:
          - ./Engine/Engine
          - ./Generator/Generator
        on:
          repo: filipefreitas8/cg1920tp
          all_branches: true
          tags: true
